# Generated by Django 5.1.15 on 2026-06-07 16:07

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name="To'liq ism")),
                ('age_group', models.CharField(choices=[('6-8', '6-8 yosh'), ('9-11', '9-11 yosh'), ('12-14', '12-14 yosh')], default='9-11', max_length=10, verbose_name='Yosh guruhi')),
                ('avatar', models.CharField(default='🦁', max_length=8, verbose_name='Avatar')),
                ('xp', models.PositiveIntegerField(default=0, verbose_name='Tajriba (XP)')),
                ('coins', models.PositiveIntegerField(default=15, verbose_name='Tangalar')),
                ('stars', models.PositiveIntegerField(default=0, verbose_name='Yulduzlar')),
                ('streak_days', models.PositiveIntegerField(default=0, verbose_name='Ketma-ket kunlar')),
                ('last_active', models.DateField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='Ovoz yoniq')),
                ('language', models.CharField(default='uz', max_length=5, verbose_name='Til')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ParentalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(default='0000', max_length=8, verbose_name='Ota-ona PIN kodi')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Nazorat yoqilgan')),
                ('daily_limit_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='Kunlik vaqt chegarasi (daqiqa)')),
                ('weekly_goal_minutes', models.PositiveSmallIntegerField(default=180, verbose_name='Haftalik maqsad (daqiqa)')),
                ('bedtime_start', models.TimeField(default=datetime.time(21, 0), verbose_name='Tunlik bloklash boshlanishi')),
                ('bedtime_end', models.TimeField(default=datetime.time(7, 0), verbose_name='Tunlik bloklash tugashi')),
                ('allow_mental', models.BooleanField(default=True, verbose_name='Mental arifmetika')),
                ('allow_xotira', models.BooleanField(default=True, verbose_name='Xotira')),
                ('allow_tezoqish', models.BooleanField(default=True, verbose_name="Tez o'qish")),
                ('allow_diqqat', models.BooleanField(default=True, verbose_name='Diqqat')),
                ('allow_matematika', models.BooleanField(default=True, verbose_name='Matematika')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Hisob bloklangan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parental', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Ota-ona nazorati',
                'verbose_name_plural': 'Ota-ona nazorati',
            },
        ),
    ]
