# Generated by Django 5.1.15 on 2026-06-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='Toshkent', max_length=60, verbose_name='Shahar'),
        ),
    ]
