# Generated by Django 5.1.15 on 2026-06-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentalcontrol',
            name='child_first_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Bola ismi'),
        ),
        migrations.AddField(
            model_name='parentalcontrol',
            name='child_last_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Bola familiyasi'),
        ),
        migrations.AddField(
            model_name='parentalcontrol',
            name='parent_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Yoshi'),
        ),
        migrations.AddField(
            model_name='parentalcontrol',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (Gmail)'),
        ),
        migrations.AddField(
            model_name='parentalcontrol',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ota-ona ismi'),
        ),
        migrations.AddField(
            model_name='parentalcontrol',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ota-ona familiyasi'),
        ),
        migrations.AddField(
            model_name='parentalcontrol',
            name='parent_type',
            field=models.CharField(choices=[('ota', 'Ota'), ('ona', 'Ona')], default='ota', max_length=4, verbose_name='Kim'),
        ),
        migrations.AddField(
            model_name='parentalcontrol',
            name='parent_workplace',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ish joyi'),
        ),
        migrations.AddField(
            model_name='parentalcontrol',
            name='registered',
            field=models.BooleanField(default=False, verbose_name="Ro'yxatdan o'tgan"),
        ),
    ]
