# Generated by Django 5.1.15 on 2026-06-07 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Kod')),
                ('title', models.CharField(max_length=80, verbose_name='Nomi')),
                ('description', models.CharField(max_length=160, verbose_name='Tavsif')),
                ('icon', models.CharField(default='🏅', max_length=8, verbose_name='Belgi')),
                ('coins', models.PositiveIntegerField(default=50, verbose_name='Mukofot tangalar')),
            ],
            options={
                'verbose_name': 'Yutuq',
                'verbose_name_plural': 'Yutuqlar',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=80, verbose_name='Nomi')),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='Kategoriya')),
                ('kind', models.CharField(default='quiz', max_length=20, verbose_name="O'yin turi (React)")),
                ('short_title', models.CharField(blank=True, max_length=40, verbose_name='Qisqa nomi')),
                ('tagline', models.CharField(blank=True, max_length=160, verbose_name='Shior')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('skill', models.CharField(blank=True, max_length=80, verbose_name="Ko'nikma")),
                ('icon', models.CharField(default='🎮', max_length=8, verbose_name='Belgi (emoji)')),
                ('color', models.CharField(default='#14b8a6', max_length=20, verbose_name='Asosiy rang')),
                ('color_2', models.CharField(default='#0ea5e9', max_length=20, verbose_name='Ikkilamchi rang')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "O'yin",
                'verbose_name_plural': "O'yinlar",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Ball')),
                ('coins_earned', models.PositiveIntegerField(default=0, verbose_name='Yutilgan tangalar')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='Yutilgan XP')),
                ('stars_earned', models.PositiveIntegerField(default=0, verbose_name='Yutilgan yulduzlar')),
                ('questions_total', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('questions_correct', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Davomiyligi (s)')),
                ('difficulty_start', models.PositiveSmallIntegerField(default=1, verbose_name="Boshlang'ich daraja")),
                ('difficulty_end', models.PositiveSmallIntegerField(default=1, verbose_name='Yakuniy daraja')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessiya',
                'verbose_name_plural': 'Sessiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200, verbose_name='Savol')),
                ('correct_answer', models.CharField(max_length=120, verbose_name="To'g'ri javob")),
                ('user_answer', models.CharField(blank=True, max_length=120, verbose_name='Foydalanuvchi javobi')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri")),
                ('difficulty', models.PositiveSmallIntegerField(default=1, verbose_name='Daraja')),
                ('time_ms', models.PositiveIntegerField(default=0, verbose_name='Sarflangan vaqt (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.gamesession')),
            ],
            options={
                'verbose_name': 'Urinish',
                'verbose_name_plural': 'Urinishlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, verbose_name='Joriy daraja')),
                ('best_score', models.PositiveIntegerField(default=0, verbose_name='Eng yaxshi natija')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='Sessiyalar')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Savollar')),
                ('total_correct', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('total_seconds', models.PositiveIntegerField(default=0, verbose_name='Sarflangan vaqt (s)')),
                ('streak', models.SmallIntegerField(default=0, verbose_name='Joriy ketma-ketlik')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progress',
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
